const { GoogleSpreadsheet } = require("google-spreadsheet");
const { JWT } = require("google-auth-library");

async function updateGoogleSheets(
  secrets,
  googleSpreadsheetId,
  sheetName,
  extractedData
) {
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: secrets.client_email,
    key: secrets.private_key,
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
  });

  let doc;
  try {
    doc = new GoogleSpreadsheet(googleSpreadsheetId, serviceAccountAuth);
    await doc.loadInfo();
  } catch (error) {
    return "Invalid Sheet Link, please check the google sheet link" + error;
  }
  console.log("doc", doc);

  console.log(doc.title);

  let sheet = doc.sheetsByTitle[sheetName];
  if (sheet === undefined || sheet === null) {
    sheet = await doc.addSheet({ headerValues: Object.keys(extractedData[0]) });
    await sheet.updateProperties({ title: sheetName });
  }

  console.log(sheet.title);

  // sheet.loadHeaderRow();
  sheet.addRows(extractedData);

  return "success";
}

module.exports = updateGoogleSheets;
